### PR TITLE
Side effects false

### PR DESCRIPTION
**Pull request by jeetiss**
this is my second take on how to make library side effects free. (first one #63)

### CODE REVIEW

**Comment by jeetiss** [comment]
I tested the bundle size difference for `sideEffects: false` separately and it doesn't change anything at all, lol)

so I going to close this PR

**Comment by steveluscher** [comment]
This is still worth doing. It's not that it will make _this_ library smaller, it's that if `@noble/hashes` ever becomes unreachable in the application of which it's a dependency, that application's bundle will be able to reap _the entire thing_.

Without `sideEffects: false`, the bundler will assume that merely doing `import { ... } from '@noble/hashes'` mutates the environment in some important way (which it does not) and will _keep_ all the code.

**Comment by jeetiss** [comment]
> This is still worth doing. It's not that it will make this library smaller, it's that if @noble/hashes ever becomes unreachable in the application of which it's a dependency, that application's bundle will be able to reap the entire thing.

yes, but `@noble/hashes` contains side effects and it is not safe to drop it completely

there is a side effect:
https://github.com/paulmillr/noble-hashes/blob/main/src/utils.ts#L27-L32

**Comment by steveluscher** [comment]
The side effect being the thrown error?

**Comment by jeetiss** [comment]
yes, thrown an error on a module level

**Comment by steveluscher** [comment]
If all of `@noble/hashes` is dead code in the application that takes as a dependency, I think it would be appropriate _not_ to throw that error, don't you?

**Comment by paulmillr** [comment]
So, how should the app behave on unsupported architectures then? Are you suggesting its methods should just corrupt data?

**Comment by steveluscher** [comment]
In the case [described here](https://github.com/paulmillr/noble-hashes/pull/68#issuecomment-1615018402) the whole library would be reaped by the compiler. There would be no methods left to call.

**Comment by paulmillr** [comment]
I don't see how we can have one thing without another. `isLE` is side-effect.

Runtime in-hash checks for little-endianness can't be done, because that would screw up perf - which was very thoroughly tested.

**Comment by steveluscher** [comment]
Here's an example.

```ts
import { bytesToHex } from '@noble/hashes/utils';

export getRandomBytes() {
  const bytes = // Get some random bytes however you like.
  if (__DEV__) {
    console.log(`Generated random bytes: ${bytesToHex(bytes)}`);
  }
  return bytes;
}
```

When your compiler injects `true` for `__DEV__` you get this compiled output:

```ts
import { bytesToHex } from '@noble/hashes/utils';

export getRandomBytes() {
  const bytes = // Get some random bytes however you like.
  console.log(`Generated random bytes: ${bytesToHex(bytes)}`);
  return bytes;
}
```

When your compiler injects `false` for `__DEV__` you get this compiled output:

```ts
import { bytesToHex } from '@noble/hashes/utils';

export getRandomBytes() {
  const bytes = // Get some random bytes however you like.
  return bytes;
}
```

Event though every bit of `@noble/hashes/utils` became dead code, the compiler did not eliminate it. The _reason_ is because it didn't find `"sideEffects": false` in the package.json.

If you add it, then the compiler will gladly remove the import in the second case.

**Comment by paulmillr** [comment]
@steveluscher I hear you, but you don't hear me. Adding `sideEffects: false` would remove isLE check and its error throwing on unsupported architectures. Yes, it's unfortunate that for some cases it would follow inefficient tree-shaking, but I don't see how the check could be executed otherwise.

**Comment by steveluscher** [comment]
I'm trying!

I don't understand why the `isLE` check should still run when the app has no need to produce hashes, as in the bottom example I gave.

This is separate from my _general_ inclination for module _factories_ to be side-effect free, which you know by now to predict from me, when you said this:

> Runtime in-hash checks for little-endianness can't be done, because that would screw up perf - which was very thoroughly tested.

That's fair! I'd be curious if you could preserve the library's performance characteristics by doing something like this:

```ts
function getEndianness() {
  return new Uint8Array(new Uint32Array([0x11223344]).buffer)[0] === 0x44
    ? 'le'
    : 'be';
}
let endianness: 'be' | 'le' | undefined;

function hashStuff() {
  if ((endianness ||= getEndianness()) !== 'le') {
    throw new Error('Non little-endian hardware is not supported');
  }
  // Produce hash…
}
```

In _any_ case, _just_ adding `"sideEffects": false` would remove the endianness check in the sole case where endianness no longer matters.

**Comment by paulmillr** [comment]
>In any case, just adding "sideEffects": false would remove the endianness check in the sole case where endianness no longer matters.

As far as I understood, @jeetiss mentioned that adding `sideEffects: false` would always remove the isLE variable and the if-error from a bundle.

**Comment by steveluscher** [comment]
Nope! It would not, because it's used in that `if()` statement.

Compare this: ([link](https://esbuild.github.io/try/#dAAwLjE4LjEwAHt0cmVlU2hha2luZzogdHJ1ZX0ALy8gYmlnLWVuZGlhbiBoYXJkd2FyZSBpcyByYXJlLiBKdXN0IGluIGNhc2Ugc29tZW9uZSBzdGlsbCBkZWNpZGVzIHRvIHJ1biBoYXNoZXM6Ci8vIGVhcmx5LXRocm93IGFuIGVycm9yIGJlY2F1c2Ugd2UgZG9uJ3Qgc3VwcG9ydCBCRSB5ZXQuCmNvbnN0IGlzTEUgPSAvKiBAX19QVVJFX18gKi8gKCgpID0+IG5ldyBVaW50OEFycmF5KG5ldyBVaW50MzJBcnJheShbMHgxMTIyMzM0NF0pLmJ1ZmZlcilbMF0gPT09IDB4NDQpKCk))
To this: ([link](https://esbuild.github.io/try/#dAAwLjE4LjEwAHt0cmVlU2hha2luZzogdHJ1ZX0ALy8gYmlnLWVuZGlhbiBoYXJkd2FyZSBpcyByYXJlLiBKdXN0IGluIGNhc2Ugc29tZW9uZSBzdGlsbCBkZWNpZGVzIHRvIHJ1biBoYXNoZXM6Ci8vIGVhcmx5LXRocm93IGFuIGVycm9yIGJlY2F1c2Ugd2UgZG9uJ3Qgc3VwcG9ydCBCRSB5ZXQuCmNvbnN0IGlzTEUgPSAvKiBAX19QVVJFX18gKi8gKCgpID0+IG5ldyBVaW50OEFycmF5KG5ldyBVaW50MzJBcnJheShbMHgxMTIyMzM0NF0pLmJ1ZmZlcilbMF0gPT09IDB4NDQpKCkKaWYgKCFpc0xFKSB0aHJvdyBuZXcgRXJyb3IoJ05vbiBsaXR0bGUtZW5kaWFuIGhhcmR3YXJlIGlzIG5vdCBzdXBwb3J0ZWQnKTs))

**Comment by steveluscher** [comment]
In short, `"sideEffects": false` has _zero_ effect on tree-shakability inside a module, and everything to do with whether a module _itself_ is reapable at the boundary between two modules.

**Comment by paulmillr** [comment]
If what you're saying is also true for other bundlers, then I see zero reasons not to add `sideEffects: false` to package.json.

**Comment by steveluscher** [comment]
Thank you! That's all I came here to achieve.

**Comment by steveluscher** [comment]
Do you want to put this PR back up @jeetiss, so that Paul can merge it, or would you like me to?

**Comment by paulmillr** [comment]
e37b278

**Pull request closed without merging**
